with open('backend/app/services/verification.py', 'r') as f: content = f.read()
content = content.replace('return {\\n                \"best_index\"', 'return {\n                \"best_index\"')
content = content.replace('{\\n', '{\n')
content = content.replace('schema (no markdown, no quotes around the json):\\n', 'schema (no markdown, no quotes around the json):\n')
content = content.replace('candidates.\\n\\n', 'candidates.\n\n')
content = content.replace('<int>,\\n', '<int>,\n')
content = content.replace('perfect match>,\\n', 'perfect match>,\n')
content = content.replace('fits>"\\n', 'fits>"\n')
content = content.replace('Topic: {topic}\\nScene', 'Topic: {topic}\nScene')
content = content.replace('Scene Text: {scene_text}\\n\\nCandidates', 'Scene Text: {scene_text}\n\nCandidates')
with open('backend/app/services/verification.py', 'w') as f: f.write(content)
